name: ðŸ“¦ Kaoto VSIX Snapshot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ‘·ðŸ» Checkout Repository
        uses: actions/checkout@v6

      - name: âš™ï¸ Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "yarn"

      - name: ðŸ”§ Install
        run: yarn --network-timeout 1000000

      - name: ðŸ”§ Build:dev
        run: yarn build:dev

      - name: ðŸ”§ Build:prod
        run: yarn build:prod

      - name: ðŸ›  Read version from package.json
        id: version
        run: |
          VERSION=$(node -p 'require("./package.json").version')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: ðŸ›  Pack extension
        run: yarn vsce package --no-dependencies --yarn -o vscode-kaoto-${{ steps.version.outputs.version }}-SNAPSHOT.vsix

      - name: ðŸ’¾ Upload VSIX
        uses: actions/upload-artifact@v5
        with:
          name: vscode-kaoto-${{ steps.version.outputs.version }}-SNAPSHOT.vsix
          path: vscode-kaoto-${{ steps.version.outputs.version }}-SNAPSHOT.vsix
